In [1]:
import sys
import numpy as np

In [3]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [6]:
a = np.array([1, 2, 3 ,4 ])
a

array([1, 2, 3, 4])

In [7]:
b = np.array([1, .5, 2, 1.5, 0])
b

array([1. , 0.5, 2. , 1.5, 0. ])

In [8]:
a[0], a[1]

(1, 2)

In [21]:
a[0:]

array([1, 2, 3, 4])

In [25]:
a[1:4]

array([2, 3, 4])

In [27]:
a[1:-1]

array([2, 3])

In [32]:
a[::2]

array([1, 3])

In [34]:
a[0], a[2], a[-1]

(1, 3, 4)

In [35]:
a[[0, 2, -1]]

array([1, 3, 4])

In [38]:
b.dtype

dtype('float64')

In [43]:
c = np.array([[1, 2, 3],
              [4, 5, 6]])

In [44]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
c.shape

(2, 3)

In [46]:
c.ndim

2

In [47]:
c.size

6

In [49]:
c[1,1]

5

In [50]:
c[:, :2]

array([[1, 2],
       [4, 5]])

In [54]:
c[1] = 0
c

array([[1, 2, 3],
       [0, 0, 0]])

In [57]:
c[1] = np.array([7, 8, 9])
c

array([[1, 2, 3],
       [7, 8, 9]])

In [59]:
c.sum()

30

In [65]:
c.sum(axis=0)

array([ 8, 10, 12])

In [61]:
c.max()

9

In [62]:
c.min()

1

In [63]:
c.mean()

5.0

In [64]:
c.std()

3.1091263510296048

In [66]:
a

array([1, 2, 0, 4])

In [67]:
# returns a new array based on original array
a + 1

array([2, 3, 1, 5])

In [68]:
# returns a new array based on original array
a * 2

array([2, 4, 0, 8])

In [69]:
# mutates original array
a += 1

In [70]:
a

array([2, 3, 1, 5])

In [71]:
a *= 2

In [72]:
a

array([ 4,  6,  2, 10])

In [79]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [80]:
a + b

array([5, 7, 9])

In [81]:
a

array([1, 2, 3])

# This is important

In [82]:
a[[True, False, True]]

array([1, 3])

In [83]:
a >= 2

array([False,  True,  True])

In [85]:
a[a>=2]

array([2, 3])

In [86]:
a[a > a.mean()]

array([3])

In [88]:
# this is a not operator
a[~(a > a.mean())]

array([1, 2])

In [89]:
a[(a == 2) | (a == 3)] # or

array([2, 3])

In [91]:
a[(a >= 2) & (a < 5)] # and

array([2, 3])